// src/lib/client/Header.svelte
<script lang="ts">
	import { applyAction, enhance } from '$app/forms';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import { sessionRemovePrivateKey } from '$lib/client/cryptography/PrivateKey';
	import Button from './components/Button.svelte';

	let { user }: { user?: { id: string } } = $props();
</script>

<svelte:head>
	<title>Plakkert</title>
</svelte:head>
<header>
	<div id="brand">
		<img src="/icon.svg" alt="Logo" width="24" height="24" />
		<h1>Plakkert</h1>
	</div>
	{#if user}
		<nav>
			<a href={resolve('/')} aria-current={page.url.pathname === '/'}>Notes</a>
			<a href={resolve('/settings')} aria-current={page.url.pathname === '/settings'}>Settings</a>
		</nav>
		<!-- <p>Your user ID is {user.id}.</p> -->
		<form
			method="post"
			action="/?/signOut"
			use:enhance={() => {
				return async ({ result }) => {
					if (result.type === 'redirect') {
						sessionRemovePrivateKey();
					}
					await applyAction(result);
				};
			}}
		>
			<Button class="sm" --bg="var(--color-red)" type="submit">Sign out</Button>
		</form>
	{/if}
</header>

<style>
	header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		background: var(--color-background-header);
		padding: var(--spacing-md) var(--spacing-lg);

		#brand {
			display: flex;
			align-items: center;
			gap: var(--spacing-sm);
			margin-right: var(--spacing-3xl);

			h1 {
				font-family: var(--font-family-display);
				font-size: 1.5rem;
				line-height: 1;
				margin: 0;
				margin-block: 0;
			}
		}

		nav {
			display: flex;
			align-items: stretch;
			font-family: var(--font-family-display);
			flex: 1;
			gap: var(--spacing-md);
			font-size: 1.05rem;

			a {
				display: block;
				text-decoration: none;
				color: var(--color-text);
				padding: var(--spacing-sm) var(--spacing-md);
				border-radius: var(--radius-lg);
				opacity: 0.7;
				transition: opacity var(--transition-duration) ease;

				&[aria-current='true'] {
					opacity: 1;
				}

				&:not([aria-current='true']):hover {
					background-color: #fff1;
					opacity: 1;
				}
			}
		}

		p {
			margin: 0;
			margin-block: 0;
		}
	}
</style>

// src/Header.tsx
import React from "react";
import styled from "styled-components";
import { MdAddBox, MdSearch } from "react-icons/md";
import logo from "./logo.svg";

const HeaderElement = styled.header`
  display: flex;
  align-items: center;
  margin-bottom: 10px;
`;

const Logo = styled.img`
  width: 0.75em;
  height: 0.75em;
`;

const Title = styled.h1`
  margin: 0 0 0 2rem;
  font-weight: 100;
  text-transform: uppercase;
  color: #918888;
`;

const NewPlakkert = styled.button`
  display: flex;
  align-items: center;
  background: #999;
  color: #111;
  border: none;
  font-family: inherit;
  font-size: 1.2em;
  font-weight: 200;
  padding: 4px 16px;
  margin-left: 2em;
  cursor: pointer;

  &:hover {
    background: #eee;
  }

  svg {
    margin-right: 0.5em;
  }
`;

const SearchBar = styled.div`
  background-color: #6666;
  box-shadow: #3339 2px 2px 0px;
  padding: 2px 16px;
  margin: 0 1em 0 2em;
  max-width: 70ch;
  flex: 1;
  white-space: nowrap;
  border-radius: 2px;
`;

const SearchInput = styled.input`
  background: transparent;
  border: none;
  color: inherit;
  font-family: inherit;
  font-size: 1.2em;
  font-weight: 200;
  margin-left: 0.5em;
  min-width: 90%;

  &:active,
  &:focus {
    border: none;
    outline: none;
  }
`;

const Header: React.FC<{
  createNote: () => void;
}> = ({ createNote }) => {
  return (
    <HeaderElement>
      <Title>
        <Logo src={logo} alt="logo" /> Plakkert
      </Title>
      <NewPlakkert onClick={createNote}>
        <MdAddBox /> New plakkert
      </NewPlakkert>
      <SearchBar>
        <MdSearch color="#999" />
        <SearchInput type="text" placeholder="Search" />
      </SearchBar>
    </HeaderElement>
  );
};

export default Header;
